apiVersion: v1
kind: Pod
metadata:
  name: move-pod
spec:
  containers:
  - name: main
    image: byeongjokim/worker:0.1.0
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "sleep infinity" ]
    volumeMounts:
    - name: nfs-volume
      mountPath: /data
  volumes:
  - name: nfs-volume
    persistentVolumeClaim:
      claimName: nfs-pvc