name: 'Project2 CI/CD pipeline'

on:
  workflow_dispatch:
  pull_request:
    branches:
      - project2

permissions:
  contents: read
  pull-requests: read
  id-token: write

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: 'project2'
      - name: Login to GCR
        uses: docker/login-action@v3
        with:
          registry: asia-northeast3-docker.pkg.dev
          username: __json_key
          password: ${{ secrets.GCP_KEY }}
      - name: Docker build
        run: docker build . -t asia-northeast3-docker.pkg.dev/mlops-project-417801/docker/mlops-app
      - name: Docker push
        run: docker push asia-northeast3-docker.pkg.dev/mlops-project-417801/docker/mlops-app
      
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo 'deploying...'
    
