name: 'Project2 CI/CD pipeline'

on:
  workflow_dispatch:
  push:
    branches:
      - mlops-library
  pull_request:
    branches:
      - project2

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - run: echo 'dockerizing...'
      - run: echo 'registry push'
      - run: echo 'deploying...'
  
