name: 'Project2 CI/CD pipeline'

on:
  workflow_dispatch:
  pull_request:
    branches:
      - project2

permissions:
  contents: read
  pull-requests: read
  id-token: write

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      working-dir: ./2_nlp_model_serving/mlops-app
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: 'project2'
      - name: Login to Google Artifact Registry(GAR)
        uses: docker/login-action@v3
        with:
          registry: asia-northeast3-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_KEY }}
      - name: Docker build and push
        run: |
          docker build . -t asia-northeast3-docker.pkg.dev/mlops-project-417801/docker/mlops-app
          
          docker push asia-northeast3-docker.pkg.dev/mlops-project-417801/docker/mlops-app
        working-directory: ${{ env.working-dir }}
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo 'deploying...'
    
